services:
  buggybot:
    image: baboucheone/buggybot:latest
    container_name: buggybot
    env_file:
      - .env.prod
    ports:
      - "27017"
    volune:
      - /etc/localtime:/etc/localtime:ro
    restart: always
